version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.22.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test

  deploy_qa:
    docker:
      - image: circleci/node:10.22.0
    steps:
      - checkout
      - run:
          name: Install Vercel
          command: sudo npm i -g vercel
      - run:
          name: Deploy App in Vercel
          command: |
            URL=$(vercel --public -t $VERCEL_TOKEN --confirm)
            echo $URL
            curl --silent -L $URL

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - manual_approve:
          type: approval
          requires:
            - build
      - deploy_qa:
          requires:
            - manual_approve